import React from 'react'

function PrivacyTerms() {
  return (
    <div>
        <div className='text-container '>
            <h1 >PRIVACY TERMS</h1>
            <h3>PRIVACY TERMS

ROCKSTAR COLD CALLERS (“COMPANY”) IS COMMITTED TO PRIORITIZING THE PRIVACY AND SECURITY OF OUR CLIENTS’ DATA, INCLUDING ALL LISTS, DIALERS, AND TRANSACTIONS BETWEEN THE COMPANY AND ITS CLIENTS. THESE PRIVACY TERMS OUTLINE THE MEASURES WE TAKE TO PROTECT THE CONFIDENTIALITY AND INTEGRITY OF OUR CLIENTS’ INFORMATION. BY ENGAGING OUR SERVICES, CLIENTS AGREE TO ADHERE TO THE FOLLOWING PRIVACY TERMS:</h3>

    <p className='animate__animated animate__bounceInUp  animate__delay-.5s' >
   1-CONFIDENTIALITY AND NON-DISCLOSURE: THE COMPANY ACKNOWLEDGES THE SENSITIVE NATURE OF OUR CLIENTS’ DATA AND AGREES TO TREAT ALL CLIENT INFORMATION AS STRICTLY CONFIDENTIAL. WE WILL NOT DISCLOSE, SELL, OR SHARE ANY CLIENT DATA, INCLUDING LISTS, DIALERS, OR TRANSACTION DETAILS, WITH ANY THIRD PARTIES WITHOUT THE EXPLICIT CONSENT OF THE CLIENT.
   </p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s' >2-DATA SECURITY MEASURES: THE COMPANY IMPLEMENTS ROBUST TECHNICAL AND ORGANIZATIONAL MEASURES TO SAFEGUARD CLIENT DATA FROM UNAUTHORIZED ACCESS, LOSS, OR ALTERATION. WE EMPLOY INDUSTRY-STANDARD SECURITY PROTOCOLS, INCLUDING ENCRYPTION, SECURE STORAGE, ACCESS CONTROLS, FIREWALLS, AND INTRUSION DETECTION SYSTEMS, TO PROTECT CLIENT INFORMATION.</p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s'>3-LIMITED ACCESS: ACCESS TO CLIENT DATA, INCLUDING LISTS, DIALERS, AND TRANSACTION DETAILS, IS LIMITED TO AUTHORIZED PERSONNEL WHO REQUIRE THE INFORMATION TO PERFORM THEIR DUTIES. ALL EMPLOYEES AND CONTRACTORS ARE BOUND BY STRICT CONFIDENTIALITY AGREEMENTS AND WILL ACCESS CLIENT DATA ONLY AS NECESSARY TO FULFILL THEIR RESPONSIBILITIES.</p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s'  >4-DATA USAGE RESTRICTIONS: THE COMPANY WILL USE CLIENT DATA SOLELY FOR THE PURPOSE OF PROVIDING SERVICES AS AGREED UPON WITH THE CLIENT. WE WILL NOT UTILIZE CLIENT DATA FOR ANY OTHER PURPOSES OR DISCLOSE IT TO ANY THIRD PARTIES, EXCEPT AS REQUIRED TO FULFILL OUR CONTRACTUAL OBLIGATIONS OR WITH THE CLIENT’S EXPLICIT CONSENT.</p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s' >5-DATA RETENTION: THE COMPANY RETAINS CLIENT DATA, INCLUDING LISTS, DIALERS, AND TRANSACTION DETAILS, ONLY FOR AS LONG AS NECESSARY TO FULFILL THE AGREED-UPON SERVICES OR AS REQUIRED BY APPLICABLE LAWS AND REGULATIONS. ONCE THE RETENTION PERIOD EXPIRES, WE SECURELY DISPOSE OF OR ANONYMIZE CLIENT DATA TO PREVENT UNAUTHORIZED ACCESS.</p>
     <p  className='animate__animated animate__bounceInUp  animate__delay-.5s'>6-COMPLIANCE WITH LAWS: THE COMPANY COMPLIES WITH ALL APPLICABLE DATA PROTECTION LAWS AND REGULATIONS GOVERNING THE COLLECTION, STORAGE, AND PROCESSING OF PERSONAL DATA. WE ASSIST CLIENTS IN MEETING THEIR LEGAL OBLIGATIONS, INCLUDING RESPONDING TO DATA SUBJECT REQUESTS, AS REASONABLY REQUIRED.</p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s' >7-SUBCONTRACTORS AND THIRD PARTIES: IN CERTAIN CASES, THE COMPANY MAY ENGAGE SUBCONTRACTORS OR THIRD-PARTY SERVICE PROVIDERS TO ASSIST IN DELIVERING SERVICES TO CLIENTS. WE ENSURE THAT THESE ENTITIES ADHERE TO THE SAME HIGH STANDARDS OF DATA PROTECTION AND CONFIDENTIALITY AS OUTLINED IN THESE PRIVACY TERMS.</p>
     <p className='animate__animated animate__bounceInUp  animate__delay-.5s' >8-BREACH NOTIFICATION: IN THE EVENT OF A DATA BREACH THAT MAY RESULT IN THE UNAUTHORIZED ACQUISITION, ACCESS, OR DISCLOSURE OF CLIENT DATA, THE COMPANY WILL PROMPTLY NOTIFY THE AFFECTED CLIENT AND TAKE IMMEDIATE STEPS TO MITIGATE THE EFFECTS OF SUCH BREACH.</p>
     <p  className='animate__animated animate__bounceInUp  animate__delay-.5s'>9-MODIFICATION OF PRIVACY TERMS: THESE PRIVACY TERMS MAY BE MODIFIED OR AMENDED ONLY BY WRITTEN AGREEMENT BETWEEN THE COMPANY AND THE CLIENT.</p>
        </div>
    </div>
  )
}

export default PrivacyTerms